variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Vị trí cache cho SonarCloud
  GIT_DEPTH: "0"                               # Lấy toàn bộ lịch sử git, cần thiết cho phân tích

sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner \
      -Dsonar.projectKey=$SONAR_PROJECT_KEY \
      -Dsonar.organization=$SONAR_ORGANIZATION \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.login=$SONAR_TOKEN
